import { JournalEntry, TrackerSnapshot, Workout, DailySummary, Insight } from './types'

export const TODAY = '2026-04-12'

export const dummyTrackerSnapshot: TrackerSnapshot = {
  date: TODAY,
  hrv_ms: 42,
  hrv_avg_14d: 52,
  sleep_hours: 6.2,
  sleep_avg_14d: 7.2,
  sleep_score: 71,
  resting_hr: 61,
  resting_hr_avg_30d: 54,
  steps: 8432,
  steps_avg_14d: 9200,
  deep_sleep_pct: 14,
}

export const dummyWorkout: Workout = {
  id: 'w1',
  workout_type: 'Running',
  started_at: '2026-04-12T17:30:00Z',
  ended_at: '2026-04-12T18:04:00Z',
  duration_mins: 34,
  distance_km: 5.4,
  calories_active: 412,
  avg_hr: 172,
  max_hr: 188,
}

export const dummyEntries: JournalEntry[] = [
  {
    id: 'e1',
    entry_type: 'drink',
    description: 'Black coffee',
    quantity: '1 cup',
    logged_at: '2026-04-12T08:00:00Z',
    created_at: '2026-04-12T08:02:00Z',
    status: 'confirmed',
    source: 'voice',
  },
  {
    id: 'e2',
    entry_type: 'supplement',
    description: 'Iron supplement',
    quantity: '65mg',
    logged_at: '2026-04-12T08:15:00Z',
    created_at: '2026-04-12T08:16:00Z',
    status: 'confirmed',
    source: 'voice',
  },
  {
    id: 'e3',
    entry_type: 'food',
    description: 'Eggs + toast',
    quantity: '2 eggs, 2 slices',
    logged_at: '2026-04-12T08:30:00Z',
    created_at: '2026-04-12T08:31:00Z',
    status: 'confirmed',
    source: 'voice',
    macros: { calories: 340, protein_g: 18, carbs_g: 30, fat_g: 14 },
  },
  {
    id: 'e4',
    entry_type: 'supplement',
    description: 'Vitamin D',
    quantity: '2000 IU',
    logged_at: '2026-04-12T09:00:00Z',
    created_at: '2026-04-12T00:01:00Z',
    status: 'pending',
    source: 'habit',
  },
  {
    id: 'e5',
    entry_type: 'food',
    description: 'Grilled chicken + rice',
    quantity: '200g chicken, 1 cup rice',
    logged_at: '2026-04-12T13:00:00Z',
    created_at: '2026-04-12T13:05:00Z',
    status: 'confirmed',
    source: 'voice',
    macros: { calories: 520, protein_g: 48, carbs_g: 52, fat_g: 8 },
  },
  {
    id: 'e6',
    entry_type: 'mood',
    description: 'Feeling sluggish',
    logged_at: '2026-04-12T14:30:00Z',
    created_at: '2026-04-12T14:31:00Z',
    status: 'confirmed',
    source: 'voice',
  },
  {
    id: 'e7',
    entry_type: 'workout',
    description: '5.4km run',
    logged_at: '2026-04-12T17:30:00Z',
    created_at: '2026-04-12T17:30:00Z',
    status: 'confirmed',
    source: 'manual',
  },
  {
    id: 'e8',
    entry_type: 'supplement',
    description: 'Magnesium glycinate',
    quantity: '400mg',
    logged_at: '2026-04-12T21:00:00Z',
    created_at: '2026-04-12T00:01:00Z',
    status: 'pending',
    source: 'habit',
  },
]

export const dummyJournalEntries: JournalEntry[] = [
  {
    id: 'j1',
    entry_type: 'drink',
    description: 'Black coffee',
    quantity: '1 cup',
    logged_at: `${TODAY}T08:00:00Z`,
    created_at: `${TODAY}T08:01:00Z`,
    status: 'confirmed',
    source: 'voice',
  },
  {
    id: 'j2',
    entry_type: 'supplement',
    description: 'Iron supplement',
    quantity: '65mg',
    logged_at: `${TODAY}T08:15:00Z`,
    created_at: `${TODAY}T08:16:00Z`,
    status: 'confirmed',
    source: 'voice',
  },
  {
    id: 'j3',
    entry_type: 'food',
    description: 'Eggs and toast',
    quantity: '2 eggs, 2 slices',
    logged_at: `${TODAY}T08:45:00Z`,
    created_at: `${TODAY}T08:46:00Z`,
    status: 'confirmed',
    source: 'voice',
  },
  {
    id: 'j4',
    entry_type: 'supplement',
    description: 'Vitamin D',
    quantity: '2000 IU',
    logged_at: `${TODAY}T09:00:00Z`,
    created_at: `${TODAY}T00:01:00Z`,
    status: 'pending',
    source: 'habit',
  },
  {
    id: 'j5',
    entry_type: 'food',
    description: 'Grilled chicken salad',
    logged_at: `${TODAY}T13:00:00Z`,
    created_at: `${TODAY}T13:05:00Z`,
    status: 'confirmed',
    source: 'voice',
  },
  {
    id: 'j6',
    entry_type: 'energy',
    description: 'Feeling sluggish, low focus',
    logged_at: `${TODAY}T14:30:00Z`,
    created_at: `${TODAY}T14:31:00Z`,
    status: 'confirmed',
    source: 'voice',
  },
  {
    id: 'j7',
    entry_type: 'drink',
    description: 'Protein shake',
    quantity: '30g whey',
    logged_at: `${TODAY}T16:00:00Z`,
    created_at: `${TODAY}T16:01:00Z`,
    status: 'confirmed',
    source: 'voice',
  },
  {
    id: 'j8',
    entry_type: 'supplement',
    description: 'Magnesium glycinate',
    quantity: '400mg',
    logged_at: `${TODAY}T21:00:00Z`,
    created_at: `${TODAY}T00:01:00Z`,
    status: 'pending',
    source: 'habit',
  },
]

export const dummyInsights: Insight[] = [
  {
    type: 'warning',
    text: 'Iron supplement taken 15 mins after black coffee — iron absorption is significantly reduced. Space these by at least 1 hour.',
  },
  {
    type: 'warning',
    text: 'Zone 4/5 run (avg HR 172bpm) logged while HRV was already 19% below your 14-day baseline. High overreaching risk — consider active recovery tomorrow.',
  },
]

export const dummySummary: DailySummary = {
  date: TODAY,
  what_worked: 'Protein intake was solid — chicken + eggs covered your targets. Workout completed despite a tough morning.',
  what_was_average: 'Sleep was below your average (6.2h vs 7.2h usual). Resting HR is up 7bpm from your 30-day average — your body is under more load than usual.',
  warnings: [
    'Iron supplement taken 15 mins after black coffee — iron absorption is significantly reduced. Space these by at least 1 hour.',
    'Zone 4/5 run logged while HRV was already 19% below baseline. High overreaching risk — consider active recovery tomorrow.',
  ],
  generated_at: new Date().toISOString(),
}
