import { NextResponse } from 'next/server'
import { sql } from '@/lib/db'

/**
 * GET /api/warnings
 * Returns the most recent cached warnings from insights_cache.
 * Warnings are generated by /api/analyse and stored there.
 */
export async function GET() {
  try {
    const [row] = await sql`
      SELECT warnings, generated_at
      FROM insights_cache
      ORDER BY generated_at DESC
      LIMIT 1
    `

    if (!row) {
      return NextResponse.json({ warnings: [], generated_at: null })
    }

    const warnings: string[] = Array.isArray(row.warnings) ? row.warnings : []
    return NextResponse.json({ warnings, generated_at: row.generated_at })
  } catch (err) {
    console.error('[/api/warnings] DB error:', err)
    return NextResponse.json({ warnings: [], generated_at: null })
  }
}
